import { LabAnalysisReport, LabDocumentSourceType } from "@/types/labReport";

export function createMockLabReport(sourceType: LabDocumentSourceType): LabAnalysisReport {
  const createdAt = new Date().toISOString();

  return {
    id: `lab-report-${Date.now()}`,
    createdAt,
    sourceDocument: {
      fileName: sourceType === "sample" ? "sample-lab-report.pdf" : "uploaded-lab-report",
      mimeType: sourceType === "image" ? "image/jpeg" : "application/pdf",
      sizeBytes: null,
      sourceType,
      pageCount: 1,
      persisted: false,
    },
    language: {
      detected: "en",
      reportLanguage: "en",
    },
    patient: {
      name: null,
      sex: "female",
      ageText: "47 years",
      patientLabel: "Adult patient",
    },
    summary: {
      headline: "Iron deficiency pattern with mildly elevated A1c and otherwise stable renal markers.",
      bullets: [
        "Hemoglobin and ferritin trend low, consistent with likely iron deficiency.",
        "HbA1c is mildly elevated in the prediabetes range and should be followed up.",
        "Creatinine and eGFR appear stable, with no urgent renal signal in this sample.",
      ],
      overallRisk: "moderate",
    },
    abnormalFindings: [
      {
        id: "finding-ferritin",
        title: "Ferritin is low and may explain fatigue or reduced iron stores.",
        severity: "moderate",
        explanation:
          "Ferritin is below the stated reference range. In the context of low hemoglobin, this supports an iron-deficiency pattern rather than an isolated lab variation.",
        relatedResultIds: ["result-hemoglobin", "result-ferritin"],
        actionability: "discuss_with_clinician_soon",
      },
      {
        id: "finding-a1c",
        title: "HbA1c is mildly elevated.",
        severity: "mild",
        explanation:
          "The A1c result is above the stated normal band but not in a crisis range. It is worth discussing follow-up testing or lifestyle review with a clinician.",
        relatedResultIds: ["result-a1c"],
        actionability: "routine_follow_up_or_monitoring",
      },
    ],
    results: [
      {
        id: "result-hemoglobin",
        testNameRaw: "Hemoglobin",
        testNameCanonical: "Hemoglobin",
        panelName: "Complete blood count",
        valueRaw: "10.8",
        valueNumeric: 10.8,
        unit: "g/dL",
        referenceRangeRaw: "12.0 - 15.5",
        referenceLow: 12,
        referenceHigh: 15.5,
        flag: "low",
        severity: "moderate",
        clinicalMeaning: "Low hemoglobin can be seen with anemia and fits the low-ferritin pattern in this sample.",
        patientExplanation: "Your red blood cell oxygen-carrying level is lower than expected.",
        recommendedFollowUp: "Discuss anemia workup and iron studies with a clinician.",
        confidence: 0.95,
        pageNumber: 1,
        sourceSnippet: "Hemoglobin 10.8 g/dL (12.0 - 15.5)",
        sourceRowText: "Hemoglobin 10.8 g/dL 12.0 - 15.5",
        extractionMethod: "text",
      },
      {
        id: "result-ferritin",
        testNameRaw: "Ferritin",
        testNameCanonical: "Ferritin",
        panelName: "Iron studies",
        valueRaw: "9",
        valueNumeric: 9,
        unit: "ng/mL",
        referenceRangeRaw: "15 - 150",
        referenceLow: 15,
        referenceHigh: 150,
        flag: "low",
        severity: "moderate",
        clinicalMeaning: "Ferritin is below range and suggests low iron stores.",
        patientExplanation: "This result suggests your stored iron level is lower than expected.",
        recommendedFollowUp: "Review diet, blood loss history, and iron replacement options with a clinician.",
        confidence: 0.95,
        pageNumber: 1,
        sourceSnippet: "Ferritin 9 ng/mL (15 - 150)",
        sourceRowText: "Ferritin 9 ng/mL 15 - 150",
        extractionMethod: "text",
      },
      {
        id: "result-a1c",
        testNameRaw: "HbA1c",
        testNameCanonical: "Hemoglobin A1c",
        panelName: "Metabolic screening",
        valueRaw: "5.9",
        valueNumeric: 5.9,
        unit: "%",
        referenceRangeRaw: "4.0 - 5.6",
        referenceLow: 4,
        referenceHigh: 5.6,
        flag: "high",
        severity: "mild",
        clinicalMeaning: "A1c is mildly above the normal reference range and may warrant monitoring.",
        patientExplanation: "This blood sugar trend marker is a little higher than the standard range.",
        recommendedFollowUp: "Discuss repeat A1c or fasting glucose testing if clinically appropriate.",
        confidence: 0.93,
        pageNumber: 1,
        sourceSnippet: "HbA1c 5.9 % (4.0 - 5.6)",
        sourceRowText: "HbA1c 5.9 % 4.0 - 5.6",
        extractionMethod: "text",
      },
      {
        id: "result-creatinine",
        testNameRaw: "Creatinine",
        testNameCanonical: "Creatinine",
        panelName: "Renal function",
        valueRaw: "0.82",
        valueNumeric: 0.82,
        unit: "mg/dL",
        referenceRangeRaw: "0.50 - 1.10",
        referenceLow: 0.5,
        referenceHigh: 1.1,
        flag: "normal",
        severity: "none",
        clinicalMeaning: "Creatinine is within the stated reference range in this sample.",
        patientExplanation: "This kidney-related marker is within the listed normal range.",
        recommendedFollowUp: "Routine monitoring only unless symptoms or clinical context suggest otherwise.",
        confidence: 0.97,
        pageNumber: 1,
        sourceSnippet: "Creatinine 0.82 mg/dL (0.50 - 1.10)",
        sourceRowText: "Creatinine 0.82 mg/dL 0.50 - 1.10",
        extractionMethod: "text",
      },
    ],
    nextSteps: {
      urgentAttention: [],
      discussWithClinicianSoon: [
        "Review the low hemoglobin and ferritin results together, since they may reflect iron deficiency.",
      ],
      routineFollowUpOrMonitoring: [
        "Repeat or trend HbA1c based on clinical context.",
        "Continue routine renal monitoring if clinically indicated.",
      ],
    },
    quality: {
      missingInformation: [],
      ambiguities: [],
      warnings: ["This is a mocked lab analysis because the Qwen API key is not configured."],
      processingNotes: ["Mock output keeps the labs workflow demoable without live model inference."],
      degradedMode: false,
    },
    sourceText:
      "Adult patient laboratory panel. Hemoglobin 10.8 g/dL (12.0 - 15.5). Ferritin 9 ng/mL (15 - 150). HbA1c 5.9 % (4.0 - 5.6). Creatinine 0.82 mg/dL (0.50 - 1.10).",
    processing: {
      mode: "mock",
      usedClaude: false,
      usedMock: true,
      pageCount: 1,
      extractionModes: [{ pageNumber: 1, mode: "text" }],
    },
    provenance: {
      pagesWithExtractionFailures: [],
      failedPageCount: 0,
      extractionModel: null,
      visionModel: null,
      reasoningModel: null,
    },
  };
}
